-- Run through db/migrate.sql, not directly. This file is immutable once applied.
SET LOCAL search_path = public, pg_catalog;

-- No typmod: preserve supplied decimal precision instead of silently rounding scale.
CREATE DOMAIN finite_amount AS numeric
    CHECK (VALUE > '-Infinity'::numeric AND VALUE < 'Infinity'::numeric);
CREATE DOMAIN nonnegative_amount AS numeric
    CHECK (VALUE >= 0 AND VALUE < 'Infinity'::numeric);
CREATE DOMAIN positive_amount AS numeric
    CHECK (VALUE > 0 AND VALUE < 'Infinity'::numeric);
CREATE DOMAIN event_time AS timestamptz
    CHECK (isfinite(VALUE) AND date_trunc('milliseconds', VALUE) = VALUE);
CREATE DOMAIN nonblank_text AS text CHECK (VALUE ~ '[^[:space:]]');
CREATE DOMAIN trade_side AS text CHECK (VALUE IN ('Buy', 'Sell'));

CREATE TABLE assets (
    asset_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (asset_id > 0),
    symbol text COLLATE "C" NOT NULL UNIQUE CHECK (symbol ~ '^[A-Za-z0-9][A-Za-z0-9.-]*$'),
    name nonblank_text NOT NULL,
    currency text NOT NULL CHECK (currency = 'USD'),
    UNIQUE (asset_id, symbol)
);

CREATE TABLE market_prices (
    asset_id bigint NOT NULL REFERENCES assets(asset_id),
    observed_at event_time NOT NULL,
    source nonblank_text NOT NULL,
    adjustment text NOT NULL CHECK (adjustment IN ('raw', 'split_adjusted', 'total_return_adjusted')),
    open positive_amount NOT NULL,
    high positive_amount NOT NULL,
    low positive_amount NOT NULL,
    close positive_amount NOT NULL,
    volume nonnegative_amount NOT NULL,
    PRIMARY KEY (asset_id, observed_at, source, adjustment),
    CHECK (low <= open AND low <= close AND high >= open AND high >= close AND low <= high)
);

CREATE TABLE portfolios (
    portfolio_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (portfolio_id > 0),
    name nonblank_text NOT NULL,
    kind text NOT NULL CHECK (kind IN ('real', 'simulated')),
    currency text NOT NULL CHECK (currency = 'USD'),
    starting_cash nonnegative_amount NOT NULL
);

CREATE TABLE strategies (
    strategy_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (strategy_id > 0),
    name nonblank_text NOT NULL,
    version nonblank_text NOT NULL,
    UNIQUE (name, version),
    UNIQUE (strategy_id, version)
);

CREATE TABLE strategy_runs (
    run_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (run_id > 0),
    portfolio_id bigint NOT NULL REFERENCES portfolios(portfolio_id),
    strategy_id bigint NOT NULL,
    strategy_version nonblank_text NOT NULL,
    range_start event_time NOT NULL,
    range_end event_time NOT NULL,
    starting_capital nonnegative_amount NOT NULL,
    parameters jsonb NOT NULL CHECK (jsonb_typeof(parameters) = 'object'),
    universe jsonb NOT NULL CHECK (jsonb_typeof(universe) = 'array')
        CHECK (jsonb_array_length(universe) > 0)
        CHECK (NOT jsonb_path_exists(universe, '$[*] ? (@.type() != "string")')),
    fee_per_order nonnegative_amount NOT NULL,
    slippage_bps nonnegative_amount NOT NULL CHECK (slippage_bps <= 10000),
    adjustment text NOT NULL CHECK (adjustment IN ('raw', 'split_adjusted', 'total_return_adjusted')),
    status text NOT NULL CHECK (status IN ('planned', 'running', 'completed', 'failed')),
    CHECK (range_end >= range_start),
    FOREIGN KEY (strategy_id, strategy_version) REFERENCES strategies(strategy_id, version),
    UNIQUE (portfolio_id, run_id)
);

CREATE TABLE orders (
    portfolio_id bigint NOT NULL REFERENCES portfolios(portfolio_id),
    order_id bigint NOT NULL CHECK (order_id > 0),
    asset_id bigint NOT NULL REFERENCES assets(asset_id),
    side trade_side NOT NULL,
    quantity positive_amount NOT NULL,
    order_type text NOT NULL DEFAULT 'Market' CHECK (order_type = 'Market'),
    status text NOT NULL DEFAULT 'Pending' CHECK (status = 'Pending'),
    submitted_at event_time NOT NULL,
    strategy_run_id bigint,
    PRIMARY KEY (portfolio_id, order_id),
    FOREIGN KEY (portfolio_id, strategy_run_id) REFERENCES strategy_runs(portfolio_id, run_id),
    UNIQUE (portfolio_id, order_id, asset_id, side, quantity, submitted_at)
);

CREATE TABLE executions (
    portfolio_id bigint NOT NULL,
    order_id bigint NOT NULL,
    asset_id bigint NOT NULL,
    side trade_side NOT NULL,
    quantity positive_amount NOT NULL,
    submitted_at event_time NOT NULL,
    price positive_amount NOT NULL,
    fees nonnegative_amount NOT NULL,
    executed_at event_time NOT NULL,
    PRIMARY KEY (portfolio_id, order_id),
    FOREIGN KEY (portfolio_id, order_id, asset_id, side, quantity, submitted_at)
        REFERENCES orders(portfolio_id, order_id, asset_id, side, quantity, submitted_at),
    CHECK (executed_at >= submitted_at),
    UNIQUE (portfolio_id, order_id, asset_id, side, quantity, price, fees, executed_at)
);

CREATE TABLE transactions (
    portfolio_id bigint NOT NULL,
    replay_sequence bigint NOT NULL CHECK (replay_sequence > 0),
    order_id bigint NOT NULL,
    asset_id bigint NOT NULL,
    symbol text COLLATE "C" NOT NULL,
    side trade_side NOT NULL,
    quantity positive_amount NOT NULL,
    price positive_amount NOT NULL,
    fees nonnegative_amount NOT NULL,
    executed_at event_time NOT NULL,
    PRIMARY KEY (portfolio_id, replay_sequence),
    UNIQUE (portfolio_id, order_id),
    FOREIGN KEY (asset_id, symbol) REFERENCES assets(asset_id, symbol),
    FOREIGN KEY (portfolio_id, order_id, asset_id, side, quantity, price, fees, executed_at)
        REFERENCES executions(portfolio_id, order_id, asset_id, side, quantity, price, fees, executed_at)
);

CREATE TABLE positions (
    portfolio_id bigint NOT NULL REFERENCES portfolios(portfolio_id),
    asset_id bigint NOT NULL REFERENCES assets(asset_id),
    quantity nonnegative_amount NOT NULL,
    average_cost positive_amount,
    realized_pnl finite_amount NOT NULL,
    as_of event_time NOT NULL,
    ledger_sequence bigint NOT NULL,
    PRIMARY KEY (portfolio_id, asset_id),
    FOREIGN KEY (portfolio_id, ledger_sequence) REFERENCES transactions(portfolio_id, replay_sequence),
    CHECK ((quantity = 0 AND average_cost IS NULL) OR (quantity > 0 AND average_cost IS NOT NULL))
);

CREATE TABLE portfolio_snapshots (
    portfolio_id bigint NOT NULL REFERENCES portfolios(portfolio_id),
    as_of event_time NOT NULL,
    ledger_sequence bigint,
    cash nonnegative_amount NOT NULL,
    market_value nonnegative_amount NOT NULL,
    total_value numeric GENERATED ALWAYS AS (cash + market_value) STORED NOT NULL,
    PRIMARY KEY (portfolio_id, as_of),
    FOREIGN KEY (portfolio_id, ledger_sequence) REFERENCES transactions(portfolio_id, replay_sequence)
);

CREATE TABLE benchmark_snapshots (
    portfolio_id bigint NOT NULL,
    as_of event_time NOT NULL,
    asset_id bigint NOT NULL,
    symbol text COLLATE "C" NOT NULL DEFAULT 'SPY' CHECK (symbol = 'SPY'),
    range_start event_time NOT NULL,
    starting_capital nonnegative_amount NOT NULL,
    market_value nonnegative_amount NOT NULL,
    adjustment text NOT NULL CHECK (adjustment IN ('raw', 'split_adjusted', 'total_return_adjusted')),
    PRIMARY KEY (portfolio_id, as_of),
    FOREIGN KEY (portfolio_id, as_of) REFERENCES portfolio_snapshots(portfolio_id, as_of),
    FOREIGN KEY (asset_id, symbol) REFERENCES assets(asset_id, symbol),
    CHECK (as_of >= range_start)
);

-- The ledger is append-only even for accidental owner UPDATE/DELETE/TRUNCATE.
-- Privileged administrators can still deliberately disable/drop these protections.
CREATE FUNCTION reject_financial_record_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '23514';
END;
$$;
CREATE TRIGGER transactions_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON transactions
    FOR EACH STATEMENT EXECUTE FUNCTION reject_financial_record_change();
CREATE TRIGGER executions_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON executions
    FOR EACH STATEMENT EXECUTE FUNCTION reject_financial_record_change();

CREATE FUNCTION protect_starting_state() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.starting_cash IS DISTINCT FROM OLD.starting_cash OR
       NEW.currency IS DISTINCT FROM OLD.currency THEN
        RAISE EXCEPTION 'portfolio starting state is immutable' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER portfolios_starting_state BEFORE UPDATE ON portfolios
    FOR EACH ROW EXECUTE FUNCTION protect_starting_state();

CREATE INDEX market_prices_observed_at_idx ON market_prices(observed_at);
CREATE INDEX strategy_runs_strategy_idx ON strategy_runs(strategy_id, strategy_version);
CREATE INDEX orders_asset_idx ON orders(asset_id);
CREATE INDEX orders_run_idx ON orders(portfolio_id, strategy_run_id);
CREATE INDEX transactions_asset_idx ON transactions(asset_id, symbol);
CREATE INDEX transactions_time_idx ON transactions(portfolio_id, executed_at, replay_sequence);
CREATE INDEX positions_asset_idx ON positions(asset_id);
CREATE INDEX positions_ledger_idx ON positions(portfolio_id, ledger_sequence);
CREATE INDEX portfolio_snapshots_ledger_idx ON portfolio_snapshots(portfolio_id, ledger_sequence);
CREATE INDEX benchmark_snapshots_asset_idx ON benchmark_snapshots(asset_id, symbol);

COMMENT ON TABLE transactions IS 'Authoritative full-fill events; replay by portfolio_id, replay_sequence.';
COMMENT ON TABLE positions IS 'Rebuildable projection; ledger remains authoritative.';
COMMENT ON TABLE portfolio_snapshots IS 'Rebuildable valuation; NULL ledger_sequence means initial state.';
COMMENT ON TABLE benchmark_snapshots IS 'SPY comparison at matching portfolio snapshot time; adjustment is explicit.';
