name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        include:
          - os: windows-latest
            generator: "Visual Studio 17 2022"
            sanitizers: OFF
          - os: ubuntu-latest
            generator: "Unix Makefiles"
            sanitizers: ON

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S . -B build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=Debug -DPQL_ENABLE_SANITIZERS=${{ matrix.sanitizers }}

    - name: Build
      run: cmake --build build --config Debug

    - name: Run tests
      run: ctest --test-dir build --verbose --build-config Debug

    - name: Check code format (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update && sudo apt-get install -y clang-format
        find src test -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror
